# Generated by Django 2.2.1 on 2019-05-30 22:35

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=400)),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('tags', models.ManyToManyField(to='blog.Tag')),
                ('user', models.ForeignKey(null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
